# Generated by Django 4.2.11 on 2024-09-23 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='apiinfo',
            name='sample_data',
            field=models.JSONField(default=''),
            preserve_default=False,
        ),
    ]
